#ifndef PARAMETERS_H
#define PARAMETERS_H

#define MODEL_PATH "../model.onnx"
#define VIDEO_INPUT_PATH "../input.mp4"
#define VIDEO_OUTPUT_PATH "output.avi"

#define SHOW_INFO false
#define ENABLE_FP16 true
#define SAVE_OUTPUT_TO_VIDEO false

#define MAX_FRAMES 100

#define MODEL_BATCH_SIZE 64
#define MODEL_INPUT_CHANNELS 3
#define MODEL_INPUT_WIDTH 224
#define MODEL_INPUT_HEIGHT 224
#define MODEL_OUTPUT_CLASSES 2

#define MINIMUM_OBJECT_WIDTH 60
#define MINIMUM_OBJECT_HEIGHT 60
#define MINIMUM_INFERENNCE_CONFIDENCE 0.80f

#define RESIZE_SIZE 256
#define CROP_OFFSET 16
#define CROP_SIZE 224

#define TRANSFORM_DIVISOR 255.f

#define TRANSFORM_MEAN_R 0.485f
#define TRANSFORM_MEAN_G 0.456f
#define TRANSFORM_MEAN_B 0.406f

#define TRANSFORM_STD_DEV_R 0.229f
#define TRANSFORM_STD_DEV_G 0.224f
#define TRANSFORM_STD_DEV_B 0.225f

const int MODEL_INPUT_IMAGE_SIZE = MODEL_INPUT_CHANNELS * MODEL_INPUT_WIDTH * MODEL_INPUT_HEIGHT;
const int MODEL_INPUT_CHANNEL_SIZE = MODEL_INPUT_WIDTH * MODEL_INPUT_HEIGHT;

#endif
